spring:
   mvc:
      view:
         prefix: /WEB-INF/pages/
         suffix: .jsp

   datasource:
      url: jdbc:mysql://127.0.0.1:3307/report
      username: root
      password: 123
      driver-class-name: com.mysql.cj.jdbc.Driver
      
logging.file: report.log

es.hosts: 127.0.0.1:9200
