server:
  port: 8090
 
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/finalscheduler
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    
cn.cnnic.plan.applicationVersion: v1.0